apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  DB_HOST: bXlzcWw=  # 'mysql' in base64
  DB_USER: cm9vdA==  # 'root' in base64
  DB_PASSWORD: cGFzc3dvcmQ=  # 'password' in base64
  DB_NAME: dXNlcl9tYW5hZ2VtZW50  # 'user_management' in base64
  REDIS_URL: cmVkaXM6Ly9yZWRpczozNjc5  # 'redis://redis:6379' in base64
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: multicontainer-ums:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_NAME
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: REDIS_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/users
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /api/users
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10